[env:esp32-cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.33
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    mikalhart/TinyGPSPlus @ ^1.0.3

build_flags =
    -D TFT_ESPI_USER_SETUP_PATH=\"lib/CustomTFTConfig/User_Setup.h\"
    -DCORE_DEBUG_LEVEL=0
